name: 21st Century Life
favicon: null
layout_spectrum: 0.3938778380397707
typography_spectrum: 0.8927998926956207
title: 21st Century Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76783061-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.1150424387305975
  lightness: 0.34489492629654706
  saturation: 0.4778458948712796
  rhythmicContrast: 0.6265046093612909
purpose: []
