name: 21st Century Life
favicon: null
layout_spectrum: 0.3938778380397707
typography_spectrum: 0.79865
title: 21st Century Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76783061-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c2c18a'
    - '#4b343e'
    - '#5a7e71'
    - '#b2884f'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.2927394330035895
  rhythmicContrast: 0.8507358198985457
purpose: []
