name: 21stCentury.Life
favicon: null
layout_spectrum: 0.3938778380397707
typography_spectrum: 0.7095132730901241
title: 21stCentury.Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bf0a30'
    - '#ffffff'
    - '#002868'
    - '#d04a67'
    - '#5a527e'
  brandStrength: 0.25
  lightness: 0.094577481970191
  saturation: 0.2927394330035895
  rhythmicContrast: 0.8507358198985457
purpose: []
